jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."

  remotingSecurity:
    enabled: true

  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "chocolateen"
          name: "Hugo"
          password: ${USER_CHOCOLATEEN_PASSWORD}
        - id: "vaugie_g"
          name: "Garance"
          password: ${USER_VAUGIE_G_PASSWORD}
        - id: "i_dont_know"
          name: "Jeremy"
          password: ${USER_I_DONT_KNOW_PASSWORD}
        - id: "nasso"
          name: "Nassim"
          password: ${USER_NASSO_PASSWORD}
  
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permissions:
              - "Overall/Administer"
              - "Overall/Read"
            assignments: 
              - "chocolateen"
          - name: "ape"
            description: "Pedagogical team member"
            permissions:
              - "Job/Build"
              - "Job/Workspace"
            assignments:
              - "Jeremy"
          - name: "gorilla"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            permissions:
              - "Job/Build"
              - "Job/Workspace"
              - "Job/Create"
              - "Job/Configure"
              - "Job/Delete"
              - "Job/Move"
              - "Job/Cancel"
            assignments:
              - "Garance"
          - name: "assist"
            description: "Assistant"
            permissions:
              - "Job/Read"
              - "Job/Workspace"
            assignments:
              - "Nassim"      
  
  
jobs:
 - file: var/jenkins_home/job_dsl.groovy
